when@dev:
    web_profiler:
        toolbar: true
<<<<<<< HEAD
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

=======

    framework:
        profiler:
            collect_serializer_data: true

when@test:
>>>>>>> 78df1d0b375aabdd442fded7d2b224fcae7e86a5
    framework:
        profiler: { collect: false }
