# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

    profile_picture_directory: '%kernel.project_dir%/public/uploads'



    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    brevo_api_key: '%env(BREVO_API_KEY)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'


    
services:
    App\Security\GoogleAuthenticator:
        arguments:
            $googleClient: '@knpu.oauth2.client.google'
    # Service for LogoutListener
    App\EventListener\LogoutListener:
        tags:
            - { name: kernel.event_listener, event: security.logout }

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    Twilio\Rest\Client:
        arguments:
            $username: '%env(TWILIO_SID)%'
            $password: '%env(TWILIO_TOKEN)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add your Stripe service configuration
    App\Service\StripePaymentService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    # Email service configuration
    App\Service\EmailService:
        arguments:
            $senderEmail: '%env(MAILER_FROM)%'

    # Sms service configuration (Make sure the indentation is correct)
    App\Service\SmsService:
        arguments:
            $apiUrl: '%env(INFOBIP_API_URL)%'
            $apiKey: '%env(INFOBIP_API_KEY)%'
            $sender: '%env(INFOBIP_SMS_SENDER)%'
        
    App\Service\ChatGptService:
        arguments:
            $openAiApiKey: '%env(OPENAI_API_KEY)%'