parameters:
    stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'
    infobip.api_url: '%env(INFOBIP_API_URL)%'
    infobip.api_key: '%env(INFOBIP_API_KEY)%'
    infobip.sms_sender: '%env(INFOBIP_SMS_SENDER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add your Stripe service configuration
    App\Service\StripePaymentService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    # Email service configuration
    App\Service\EmailService:
        arguments:
            $senderEmail: '%env(MAILER_FROM)%'

    # Sms service configuration (Make sure the indentation is correct)
    App\Service\SmsService:
        arguments:
            $apiUrl: '%env(INFOBIP_API_URL)%'
            $apiKey: '%env(INFOBIP_API_KEY)%'
            $sender: '%env(INFOBIP_SMS_SENDER)%'