# config/services.yaml
parameters:
    # Add your parameters here
  
    stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Add your Stripe service configuration
    App\Service\StripePaymentService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'

    # Email service configuration
    App\Service\EmailService:
       
        arguments:
            $senderEmail: '%env(MAILER_FROM)%'